server {
    listen 80;
    server_name aliakcay.dev www.aliakcay.dev;
    root C:/Users/Administrator/Desktop/server/appserver-backend/mock_var_www/aliakcay.dev/public_html;
    index index.html index.php;

    location / {
        try_files $uri $uri/ =404;
    }
}